# Generated by Django 5.0.6 on 2024-07-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=100)),
                ('our_clients', models.BigIntegerField()),
                ('project_completed', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About_us',
            },
        ),
    ]
