# Generated by Django 5.0.6 on 2024-07-03 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_about_us_project_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_us',
        ),
    ]
