# Generated by Django 5.0.6 on 2024-07-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_work',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
