# Generated by Django 5.0.6 on 2024-07-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_image_work_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_work',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
